# Generated by Django 4.1.5 on 2023-02-05 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pateik_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="training_paid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="training_plan",
                to="pateik_app.trainingplan",
            ),
        ),
    ]
