# Generated by Django 4.1.6 on 2023-02-10 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pateik_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="availabletime",
            name="slots",
        ),
        migrations.AddField(
            model_name="availabletime",
            name="day",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pateik_app.day",
            ),
        ),
        migrations.AddField(
            model_name="availabletime",
            name="time_start",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="image",
            field=models.ImageField(default="pngwing.com.png", upload_to="images/"),
        ),
    ]
