# Generated by Django 4.1.5 on 2023-02-06 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pateik_app", "0002_alter_customer_training_paid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="name",
        ),
        migrations.AlterField(
            model_name="customer",
            name="training_paid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="training_plan",
                to="pateik_app.trainingplan",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="date",
            field=models.DateField(default="06 Feb, 2023"),
        ),
    ]
