# Generated by Django 4.1.5 on 2023-02-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pateik_app",
            "0003_remove_customer_name_alter_customer_training_paid_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="date",
            field=models.DateField(default="09 Feb, 2023"),
        ),
    ]
