# Generated by Django 4.1.6 on 2023-02-09 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pateik_app", "0004_alter_day_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="training_paid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="pateik_app.trainingplan",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="day",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="training_day",
                to="pateik_app.day",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="price",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="training_price",
                to="pateik_app.trainingplan",
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="training_plan",
                to="pateik_app.trainingplan",
            ),
        ),
        migrations.CreateModel(
            name="DateTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_start", models.TimeField()),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="pateik_app.day",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="payment",
            name="time",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="training_time",
                to="pateik_app.datetime",
            ),
        ),
        migrations.DeleteModel(
            name="Time",
        ),
    ]
