# Generated by Django 4.1.6 on 2023-02-09 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pateik_app", "0005_alter_customer_training_paid_alter_payment_day_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DateTime",
            new_name="AvailableTime",
        ),
    ]
