# Generated by Django 4.1.6 on 2023-02-09 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pateik_app", "0005_alter_customer_training_paid_alter_payment_day_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailableSlots",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slots", models.DateTimeField(default="09 Feb, 2023 19:45")),
            ],
        ),
        migrations.CreateModel(
            name="AvailableTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slots", models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name="payment",
            name="time",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="training_time",
                to="pateik_app.availabletime",
            ),
        ),
        migrations.DeleteModel(
            name="DateTime",
        ),
    ]
