# Generated by Django 4.1.6 on 2023-02-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pateik_app", "0006_availableslots_availabletime_alter_payment_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availableslots",
            name="slots",
            field=models.DateTimeField(default="09 Feb, 2023 19:46"),
        ),
    ]
